/**
 * Environment Type Declarations
 *
 * Custom ambient type declarations for the native app.
 * Covers image module imports and other global type augmentations.
 *
 * Expo's own types are handled by `expo-env.d.ts` at the project root
 * (auto-generated, gitignored). Uniwind theme types are in `uniwind.d.ts`
 * (auto-generated by Metro via the `dtsFile` option).
 *
 * @module types/env
 */

// ============================================================================
// Image Module Declarations
// ============================================================================

declare module "*.png" {
  import type { ImageSourcePropType } from "react-native";
  const value: ImageSourcePropType;
  export default value;
}

declare module "*.jpg" {
  import type { ImageSourcePropType } from "react-native";
  const value: ImageSourcePropType;
  export default value;
}

declare module "*.jpeg" {
  import type { ImageSourcePropType } from "react-native";
  const value: ImageSourcePropType;
  export default value;
}

declare module "*.svg" {
  import type { SvgProps } from "react-native-svg";
  import type { FC } from "react";
  const content: FC<SvgProps>;
  export default content;
}
